# Generated by Django 3.2.7 on 2021-09-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratehistory',
            old_name='ua_rete',
            new_name='ua_rate',
        ),
    ]
