# Generated by Django 3.2.7 on 2021-09-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ua_rete_ratehistory_ua_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratehistory',
            options={'verbose_name': 'Rate history'},
        ),
    ]
