# Generated by Django 3.2.7 on 2021-09-29 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_ratehistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratehistory',
            options={'verbose_name_plural': 'Rates history'},
        ),
        migrations.AlterField(
            model_name='ratehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
